### ISSUE TITLE
weird random crash

### ISSUE THREAD

**Issue by yoyeet961** [coop-deluxe/sm64coopdx#109]
i was hosting mariohunt and suddenly got this crash, no idea how to reproduce it since i wasnt doing anything special
![image](https://github.com/coop-deluxe/sm64coopdx/assets/85292886/421daf1f-dc77-4134-a421-fb74cdf9d8d6)

**Comment by Agent-11** [comment]
I don't trust that you aren't using a modified build.

**Comment by Flower35** [comment]
Judging from the `Stack trace`, the issue occured because some pointer, garbage collected (`sweepstep()`) by Lua, was "freed twice". Or a `NULL` pointer was passed to the `free()` function in `l_alloc()`. In any case, that's something hidden from a regular user (from script perspective).

Unfortunatelly nothing else can be deduced from that crash without detailed steps (or better a recording of the gamplay a moment before the crash happened), and without a full memory dump (which I think the `sm64coopdx` does not provide).

**Comment by yoyeet961** [comment]
> I don't trust that you aren't using a modified build.
my build has sm64coopultra v36.1.0 in the title of the window and it uses sm64coopdx v0.1.2, this is regular sm64coopdx v0.2
