### ISSUE TITLE
Fix get_texture_info I am going crazy

### ISSUE THREAD

**Issue by Fyyyyik** [coop-deluxe/sm64coopdx#138]
Why doesn't this work
```
djui_hud_set_resolution(RESOLUTION_N64)
djui_hud_render_texture(get_texture_info("phone"), 22, 32, 1, 1)
```

It's in the HUD call hook thing with HOOK_ON_HUD_RENDER. There is indeed an image file at sm64coopdx/mods/[my mod name]/textures/phone.png

It keeps saying when I log the error in the console that it can't find the texture.

How to replicate this : Just copy the code I made into a function that gets called by the hook I mentioned and put an image file in the textures folder of the mod.

This error doesn't make any sense please help.

**Comment by AgentXLP** [comment]
Is there a .tex file

**Comment by Fyyyyik** [comment]
No but isn't that generated by the game when loading the mod?

**Comment by AgentXLP** [comment]
Yes, do you have other pngs in the directory?

**Comment by Fyyyyik** [comment]
Yes, 3 pngs and their respective tex files. Those work fine. Could those be interfering?

**Comment by AgentXLP** [comment]
Delete the already generated tex files and the game will regenerate all of them properly. For some reason if there are already .tex files in a directory, the game will just skip it. This is fixed in the next update.
Also, make sure your textures have dimensions that are powers of two (e.g. 32, 64, 128, 256, 512, 1024, ect)
Otherwise trying to render them on the HUD will cause the game to crash.

**Comment by Fyyyyik** [comment]
Oh it works now! yippie! Thank you so much!
