### ISSUE TITLE
Missing includes error when compiling on Linux

### ISSUE THREAD

**Issue by retcinder** [coop-deluxe/sm64coopdx#164]
**Describe the bug**
When attempting to compile the main branch on Linux, I receive an error due to *printf functions not being found by the compiler in `src/pc/audio/audio_sdl2.c` and `src/pc/controller/controller_bind_mapping.c`. This was on a fresh clone, adding `#include <stdio.h>` to the top of the file fixed the compile error.

**To Reproduce**
1. On a Linux system, clone the repository and cd into the repo dir
2. `make` (use some threads to speed this up)
3. Error

**Expected behavior**
No errors

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 Rolling (Kernel 6.9.7-arch1-1, glibc 2.39+r52+gf8e4623421-1, ld 2.42.0)

**Additional context**
Diff I used to resolve the compile error:
```diff
diff --git a/src/pc/audio/audio_sdl2.c b/src/pc/audio/audio_sdl2.c
index b0abea7a..3255628d 100644
--- a/src/pc/audio/audio_sdl2.c
+++ b/src/pc/audio/audio_sdl2.c
@@ -2,6 +2,8 @@
 
 #include <SDL2/SDL.h>
 
+#include <stdio.h>
+
 #include "audio_api.h"
 
 static SDL_AudioDeviceID dev;
diff --git a/src/pc/controller/controller_bind_mapping.c b/src/pc/controller/controller_bind_mapping.c
index b1da32e2..123428e5 100644
--- a/src/pc/controller/controller_bind_mapping.c
+++ b/src/pc/controller/controller_bind_mapping.c
@@ -7,6 +7,7 @@
 #endif
 #endif
 
+#include <stdio.h>
 #include "controller_bind_mapping.h"
 #include "controller_api.h"
 #include "controller_sdl.h"
```

**Comment by Flower35** [comment]
This depends on your Linux distribution and how the SDL2 development files were packaged.

For example, on my distro (Void Linux), and on the MSYS2/MINGW64 Windows version, there is this useful file: `/usr/include/SDL2/SDL_config.h`
```c
/* Comment this if you want to build without any C library requirements */
#define HAVE_LIBC 1
#ifdef HAVE_LIBC

#define STDC_HEADERS 1
#define HAVE_CTYPE_H 1
#define HAVE_STDIO_H 1
#define HAVE_STRING_H 1
```

However, when I tried to cross compile a Windows 64-bit build on Linux, these were the contents of: `/usr/local/x86_64-w64-mingw32/include/SDL2/SDL_config.h`
```c
/* This is disabled by default to avoid C runtime dependencies and manifest requirements */
#ifdef HAVE_LIBC
```

So it turns out the source code relied in some places to have the standard C headers automatically included when using the SDL2 library:
```c
#include <SDL2/SDL.h>
// #include <ctype.h>
// #include <stdio.h>
// #include <string.h>
```

Since I had installed additional headers and libraries in `/usr/local/` directory without using a package manager, and that SDL2 is included in all builds (either as a Window API or a Controller Backend), then my workaround was to change the `/usr/local/x86_64-w64-mingw32/bin/sdl2-config` file in the following way:
```sh
--cflags)
# echo -I${prefix}/include/SDL2 -Dmain=SDL_main
echo -I${prefix}/include -Dmain=SDL_main -DHAVE_STDIO_H -DHAVE_STRING_H -DHAVE_CTYPE_H
```
