### ISSUE TITLE
fatal error: 'sound/sequences_offsets.inc.c' file not found #include "sound/sequences_offsets.inc.c"

### ISSUE THREAD

**Issue by ThePlayerRolo** [coop-deluxe/sm64coopdx#186]
as in title

happens whenever I try to manualy compile it for my intel Mac on Macos 10.15.7

Expected to fully compile it with no issues.

![Screen Shot 2024-07-08 at 7 36 47 PM](https://github.com/coop-deluxe/sm64coopdx/assets/175068581/8176e931-5be8-4685-9b5a-a29f2626a6c4)

**Desktop (please complete the following information):**
 - OS: MacOS X 
 - Browser: Chrome
 - Version: 10.15.7
I did all the steps on this: https://github.com/coop-deluxe/sm64coopdx/wiki/Compiling-(macOS-Intel)

**Comment by AgentXLP** [comment]
Did you clone the repo fresh or did you `git pull` the changes?

**Comment by ThePlayerRolo** [comment]
I used  the commands: git clone https://github.com/coop-deluxe/sm64coopdx.git
cd sm64coopdx

**Comment by ThePlayerRolo** [comment]
is there something  else I had to do?

**Comment by ThePlayerRolo** [comment]
I'll try downloading the zip.

**Comment by ThePlayerRolo** [comment]
I downloaded the zip and used that but it still didn't work with the same error

**Comment by ThePlayerRolo** [comment]
followed this btw: https://github.com/coop-deluxe/sm64coopdx/wiki/Compiling-(macOS-Intel)
Haven't done libjuice bc I don't know how to get that file.

**Comment by ThePlayerRolo** [comment]
I tried all three avaible main/stable versions and none of them worked.

**Comment by AgentXLP** [comment]
> I used the commands: git clone https://github.com/coop-deluxe/sm64coopdx.git cd sm64coopdx

I see. @EmeraldLoc do you have any mac wisdom here?

**Comment by Flower35** [comment]
Hi. I've had the same problem both on MSYS2 (environment targeting Windows) and on Linux (targeting Linux or cross-compiling for Windows).

I think there is some bug in the `Makefile` with how the dependencies are listed for `'sound/sequences.bin'` and for `'sound/sequences_offsets.inc.c'`, but I could not quite figure it out yet.

---

As I mentioned in a similar issue before:
https://github.com/coop-deluxe/sm64coopdx/issues/162#issuecomment-2202719643

My workaround was to enter this in to the shell:
```
$ make build/us_pc/sound/sequences.bin
```
which resolves the issue with `sound/sequences_offsets.inc.c`.

then you can go back to the regular project building process:
```
$ make
```

**Comment by robertkirkman** [comment]
Compare for reference [Dominicentek's runtime vanilla ROM sounds extraction implementation](https://github.com/Dominicentek/saturn-studio/commit/7371f20225db61778ebecfc9c572d5848eacf381#diff-e1fa343b99e13044c15576b821e8b8ed74a9f0d602d6a2a6a4aea057796c7048) which, while not absolutely perfect (readability issues, but within the realm of what I consider to be open source), is completely unaffected by this type of problem.

**Comment by Isaac0-dev** [comment]
@robertkirkman are you sure this implementation you sent actually does extract sound correctly? it seems this implementation doesn't fully extract all sm64 assets from the rom, and in some cases (like the sm64 demo data) its simply disabled as a solution

**Comment by robertkirkman** [comment]
> @robertkirkman are you sure this implementation you sent actually does extract sound correctly? it seems this implementation doesn't fully extract all sm64 assets from the rom, and in some cases (like the sm64 demo data) its simply disabled as a solution

I've been playing it in [this](https://github.com/robertkirkman/sm64ex/releases/tag/appimage-5) and neither I nor other users have noticed any **sounds** missing. That is a good point though because it's true that Dominicentek's _overall_ extractor missed several non-sound assets, like the demo data you mentioned but also a few textures, so it's hypothetically possible there could somehow be a sound missing from it that nobody has noticed yet.

**Comment by Isaac0-dev** [comment]
if the sound assets aren't being extracted correctly, but do function correctly in game, that likely means the sound data is contained with the game binary, defeating the point of the sound extraction in the first place.
but my question is whether or not this implementation does actually extract the sound correctly.
from what i can see, this only extracts textures from the rom

**Comment by robertkirkman** [comment]
> if the sound assets aren't being extracted correctly, but do function correctly in game, that likely means the sound data is contained with the game binary, defeating the point of the sound extraction in the first place. but my question is whether or not this implementation does actually extract the sound correctly. from what i can see, this only extracts textures from the rom

**no**, the sound data is **not** contained within the game binary, which careful review and testing of Dominicentek's source code can prove beyond all doubt.

The sound data is extracted from the ROM at [this](https://github.com/Dominicentek/saturn-studio/blob/studio/src/saturn/saturn_rom_extract.cpp#L277) line which he added in a [later commit](https://github.com/Dominicentek/saturn-studio/commit/68d6239c314457177c9614465068b8af7251b128#diff-8d2b900df9f1ff46ab297c6324db3bd4c50734783b55e099faf1717454180cb0R253). Sorry for not linking every single commit he made in the process of writing his implementation, but I don't blame you for being unable to identify on your own the fact that Dominicentek's binaries do **not** contain copyrighted sound data, due to the readability issues with the code.

In that line, **`data` array contains only ROM-originated data, and this function is not invoked until after the ROM is selected, and as you should be able to clearly see after spending enough time studying it, the only data this function can possibly return is data from offsets into the array that contains _only_ ROM data.**

The rest of the required proof is pretty obvious.
- ROM file is loaded from filesystem to the `stream` variable [here](https://github.com/Dominicentek/saturn-studio/blob/studio/src/saturn/saturn_rom_extract.cpp#L415)
- `stream` variable is copied into the first `data` buffer [here](https://github.com/Dominicentek/saturn-studio/blob/studio/src/saturn/saturn_rom_extract.cpp#L417)
- pieces of `data` are stored into an `std::map mio0`  [here](https://github.com/Dominicentek/saturn-studio/blob/studio/src/saturn/saturn_rom_extract.cpp#L423-L424)
- those pieces are retrieved from `mio0` and stored in `buf` [here](https://github.com/Dominicentek/saturn-studio/blob/studio/src/saturn/saturn_rom_extract.cpp#L437)
- `buf` is passed to `file_processor_apply()` [here](https://github.com/Dominicentek/saturn-studio/blob/studio/src/saturn/saturn_rom_extract.cpp#L471)

**Note** that while tracing the origin of the `file_processor` array, you would encounter some extremely huge arrays, but **the implementation of `file_processor_apply()` proves that it is _only_ used as indices into the `data` array that is passed as the first argument to `file_processor_apply()` , and the stepthrough I outlined above proves that the `data` variable there contains purely ROM-originated data that isn't present prior to running the program.**

**Comment by robertkirkman** [comment]
> @robertkirkman are you sure this implementation you sent actually does extract sound correctly? it seems this implementation doesn't fully extract all sm64 assets from the rom, and in some cases (like the sm64 demo data) its simply disabled as a solution

What's more, not only that, but it can be **objectively, conclusively proven that Dominicentek's code is _not_ failing to extract _any_ sounds that sm64ex's original build-time extractor isn't also missing, due to the resulting extracted files being identical.** Observe:
```bash
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64 $ git clone --recursive https://github.com/sm64pc/sm64ex.git sm64ex-orig
Cloning into 'sm64ex-orig'...
remote: Enumerating objects: 15365, done.
remote: Counting objects: 100% (5886/5886), done.
remote: Compressing objects: 100% (1787/1787), done.
remote: Total 15365 (delta 4474), reused 4100 (delta 4099), pack-reused 9479
Receiving objects: 100% (15365/15365), 19.99 MiB | 5.15 MiB/s, done.
Resolving deltas: 100% (7804/7804), done.
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64 $ cp baserom.us.z64 sm64ex-orig/
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64 $ cd sm64ex-orig/
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64/sm64ex-orig $ EXTERNAL_DATA=1 make -j32 >/dev/null 2>&1
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64/sm64ex-orig $ md5sum ~/.local/share/sm64ex/res/sound/* # extracted using Dominicentek's code
34dec325df1b21c27d5f5e219ac7b726  /home/tacokoneko/.local/share/sm64ex/res/sound/bank_sets
074f4d4f6696df28f6d7548f7fc4bb26  /home/tacokoneko/.local/share/sm64ex/res/sound/sequences.bin
60cf5c48e0f6c2a47690c13d2bb695c6  /home/tacokoneko/.local/share/sm64ex/res/sound/sound_data.ctl
3dd8b941b3a3c01ff2683d20a07b0223  /home/tacokoneko/.local/share/sm64ex/res/sound/sound_data.tbl
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64/sm64ex-orig $ md5sum build/us_pc/sound/bank_sets # extracted by sm64ex's build-time extractor
34dec325df1b21c27d5f5e219ac7b726  build/us_pc/sound/bank_sets
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64/sm64ex-orig $ md5sum build/us_pc/sound/sequences.bin # extracted by sm64ex's build-time extractor
074f4d4f6696df28f6d7548f7fc4bb26  build/us_pc/sound/sequences.bin
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64/sm64ex-orig $ md5sum build/us_pc/sound/sound_data.ctl # extracted by sm64ex's build-time extractor
60cf5c48e0f6c2a47690c13d2bb695c6  build/us_pc/sound/sound_data.ctl
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64/sm64ex-orig $ md5sum build/us_pc/sound/sound_data.tbl # extracted by sm64ex's build-time extractor
3dd8b941b3a3c01ff2683d20a07b0223  build/us_pc/sound/sound_data.tbl
tacokoneko@CORSAIR /mnt/Storage/Files/Application_Files/sm64/sm64ex-orig $ 
```
Note that, at least to me, the `EXTERNAL_DATA=1` codepath _specific to audio_ appears to be trivial to separate cleanly into a standalone patch that could be paired with the `EXTERNAL_DATA=0`-based codepath used by _this_ repository for everything non-audio without having to interfere with non-audio asset extraction.

**Comment by robertkirkman** [comment]
Oh and yeah my [github actions build log](https://github.com/robertkirkman/sm64ex/actions/runs/8786838885/job/24110620714) **objectively proving ROM wasn't used as an input to _my_ binary**. Kinda might go well hand in hand with the above writeup.

**Comment by ThePlayerRolo** [comment]
new error: src/pc/pc_main.c:311:34: error: parameter name omitted
void* main_game_init(UNUSED void*) {

**Comment by ThePlayerRolo** [comment]
![Screen Shot 2024-07-09 at 10 03 36 AM](https://github.com/coop-deluxe/sm64coopdx/assets/175068581/bbd6a799-ecd4-4465-bd30-7bd71df611ac)
screenshot

**Comment by ThePlayerRolo** [comment]
I also tried singling out this for like the previous file with   make  build/us_pc/src/pc/pc_main.o but no evail same error.

**Comment by EmeraldLoc** [comment]
@motoo-tobbler Didn't you handle a lot of stuff with old versions of macOS? Can you also review my Makefile changes in the dev repo to ensure I didn't mess up anything with intel?

**Comment by ThePlayerRolo** [comment]
should I close this?

**Comment by AgentXLP** [comment]
Well does it compile fine now?

**Comment by ThePlayerRolo** [comment]
yeah
