### ISSUE TITLE
src/pc/pc_main.c:311:34: error: parameter name omitted void* main_game_init(UNUSED void*) {

### ISSUE THREAD

**Issue by ThePlayerRolo** [coop-deluxe/sm64coopdx#190]
as in title 
 
While compiling this happens every time.

I expected a full compilation

![Screen Shot 2024-07-09 at 10 03 36 AM](https://github.com/coop-deluxe/sm64coopdx/assets/175068581/698595fb-5674-43e2-867b-5eea5c53e63a)

 - OS: MacOS
 - Browser:  Chrome
 - Version 10.15.7

Done with the Intel Mac Compilation tutorial

**Comment by Flower35** [comment]
Ahhh, my bad. Looks like the behaviour is different depending on the gcc/clang versions?

---

For `gcc 12.1.0` and `gcc 14.1.0` (testing on MSYS2 for Win64 and on Linux x86_64), I get no warnings, untill I specify the `-Wpedantic` flag, which prints:
```
warning: ISO C does not support omitting parameter names in function definitions before C23 [-Wpedantic]
```

However, for `gcc 9.4.0` and `clang 10.0.0` (testing on WSL, Ubuntu 20.04 LTS), I've got the same error (not a warning), even without any compiler options (like `-Wall -Wextra -Werror -Wpedantic`)
```
error: parameter name omitted
```

---

This can be easily fixed by adding any name to the (already unused) parameter in function definition:
```c
void* main_game_init(UNUSED void* dummy) {
```

**Comment by ThePlayerRolo** [comment]
how can I do this?

**Comment by ThePlayerRolo** [comment]
Oh I just needed to edit the c file. thanks!
