### ISSUE TITLE
Add support to MacOS Sonoma

### ISSUE THREAD

**Issue by osb21313** [coop-deluxe/sm64coopdx#206]
![Screenshot 2024-07-13 at 1 53 57 PM](https://github.com/user-attachments/assets/803a1182-1d76-4a4a-97f8-1828c4bc3027)

Can't open the game; unsupported...

**Comment by EmeraldLoc** [comment]
Intel or Arm? This could be because you're on an intel chip, the compiled build was made on an m series mac.

**Comment by EmeraldLoc** [comment]
Looked into universal library. Getting all the dependencies to hook properly, and doing all of it just isn't worth it. When the patch comes out I can compile coop for intel mac's via Rosetta 2.

In the meantime, since you are on intel, you should be able to compile coopdx on an intel mac just fine on the main branch! You can follow the compilation instructions [here](https://github.com/coop-deluxe/sm64coopdx/wiki/Compiling-(macOS-Intel)). Next time I'll be sure to include an intel build in the prerelease section.

**Comment by osb21313** [comment]
> Intel or Arm? This could be because you're on an intel chip, the compiled build was made on an m series mac. I can look into making a universal app.

Intel i8 (iMac Mini)
