### ISSUE TITLE
Online/Networking Api

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#235]
This would be api, that communicate with coopnet to store data. to make stuff like online leaderboards and probably a lot of other stuff.

**Comment by AgentXLP** [comment]
No

**Comment by TheMan6900** [comment]
Could something like this be theoretically implemented good?

**Comment by AgentXLP** [comment]
I should have actually explained at all instead of giving a sharp no, my bad

# 1. You would need to make an account system
This is already way out of our scope, unless mod site integration can cover this in the future.

# 2. The CoopNet servers are already under stress
A member of our team is covering server costs and I think adding a whole Lua API for storing data would add even more stress onto the servers, and slowly take up more and more storage over time.

# 3. Someone could edit a mod to augment their data
Adding something like this is a big window for cheaters to come in and edit a mod to give them insanely high scores if something like an online leaderboard was done.

# My answer now?

Still a no from me for now, **BUT** we will see when and if we get around to mod site integration.

**Comment by TheMan6900** [comment]
Maybe possibly, there could be an approval system for mods that use online?

**Comment by TheMan6900** [comment]
Like mods would have to get approved by a higher up to use online support, like be encrypted to prevent cheaters and probably a lot more precautions.
