### ISSUE TITLE
Audio Sample Bug?

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#239]
![image](https://github.com/user-attachments/assets/c07c4041-e464-4659-bfd9-989d7c2c085f)

 (only happens on 1.01)

**Comment by TheMan6900** [comment]
this also happens with getting, setting, and destroying audio

**Comment by Isaac0-dev** [comment]
thats not a bug.
the issue is that your code is destroying an audio stream/sample, then you attempt to perform actions on that said audio buffer. 
previous versions of coop had a bug, where it did not throw an error when you did this, so people probably did not know that they were doing this to their code.

**Comment by TheMan6900** [comment]
> thats not a bug. the issue is that your code is destroying an audio stream/sample, then you attempt to perform actions on that said audio buffer (even though you just destroyed it). previous versions of coop had a bug, where it did not throw an error when you did this, so people probably did not know that they were doing this to their code.

ah, I get it
