### ISSUE TITLE
Big Boo's Haunt Spawn/Collision/Crash Error

### ISSUE THREAD

**Issue by BakerIsHungry** [coop-deluxe/sm64coopdx#256]
**Describe the bug**
Big Boo's Haunt keeps spawning us into one of two wrong areas, leaving us in a black void with nowhere to go as we're trapped in a box with the area unloaded aside from objects and NPCs. Other times we spawn directly above the ground with only a few areas we can move to as if something's keeping us from touching the ground, with a pitched down/up boo laugh to taunt us. On a few rare instances, it crashes before loading the level.

**To Reproduce**
Just get to Big Boo's Haunt. Might happen, might not. It always does for me and my friends.

**Expected behavior**
Player should be able to spawn in normally.

**Screenshots**
![image](https://github.com/user-attachments/assets/40d1e2e9-5c2a-41a1-bc2a-5fca0194e168)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: 10.0.19045

**Additional context**
We were doing levels out of order, but that shouldn't have any effect on anything. I have tested the game with and without mods and the issue persists regardless. The version I'm using is OpenGL and I have no clue if this is a known bug or not, but I saw nothing on it so I figured I'd post it here. The one where it loads in the map seems to depend on the amount of mods toggled on or off, but it also seems random and that result only seemed to have happened twice, so I wasn't able to capture a screenshot of that particular result.

**Comment by BakerIsHungry** [comment]
ugh hold on windows hates fullscreen

**Comment by Krid3l** [comment]
Hey there, you're not alone! Me and my game pals also experience this issue. I'll report back if I find anything of interest.

**Comment by Krid3l** [comment]
Found something. On my end it was the [[CS] Bone Bros. v1.0](https://mods.sm64coopdx.com/mods/cs-bone-bros.296/) mod that was causing this glitch to happen.

**Comment by AgentXLP** [comment]
This is very bizzare.

**Comment by Flower35** [comment]
Hi, I was looking through any open issues and noticed I already pushed a fix for this.

https://github.com/coop-deluxe/sm64coopdx/pull/404

---

There was no guard for having too many custom models loaded in, and it just so happened that in `"sm64coopdx.exe"` global memory layout, `sCustomModels[MAX_CUSTOM_MODELS]` was immediately followed by `bbh_seg7_vertex_`, which is vertex (collision) data for "Big Boo's Haunt", extrated once from game's ROM.

Otherwise (if not for these strange side effects), the bug in code might have gone unnoticed for quite a while.

![image](https://github.com/user-attachments/assets/527787d4-ebc6-4f4d-9c56-efdcec592935)

---

I noticed it by accident while playing on a private server with a a big character pack and trying to collect 120 stars. First it looked like random Character Select mods were triggering different results, but the actual reason was just having too many of them loaded at once.

![image](https://github.com/user-attachments/assets/ef8c7bd2-a883-4d0e-ae33-7c3e80be2083)
![image](https://github.com/user-attachments/assets/2598f503-973a-490b-a235-9f9404a50282)
