### ISSUE TITLE
the game 64/32bit supporter

### ISSUE THREAD

**Issue by Tre013arabic** [coop-deluxe/sm64coopdx#266]
I got the most painful error . The game is supported for 64bitwhen my pc is 32bit 
So please Agent x fix it !!

**Comment by robertkirkman** [comment]
It is possible to compile the game for 32 bit and it works. However that is much more tedious and time consuming on Windows than it is on GNU/Linux. Before a 32-bit Windows build is released, it is probably the most convenient for you to **install GNU/Linux** because the **[32-bit version of GCC (compiler) for Windows](https://github.com/jeremyd2019/msys2-build32/blob/master/build32.sh) is unmaintained**, meaning it won't receive future updates, and looks like it's for advanced users only.

If you post your **PC specs**, that would reveal two things: compatibility with GNU/Linux, and whether your **CPU is 32-bit or not**. In 2024, **32-bit CPUs in laptop and desktop PCs are uncommon**. If your CPU is 64-bit, **reinstalling your operating system**, either Windows or GNU/Linux equally, can successfully transform your PC from 32-bit into 64-bit, **improving compatibility with other games, not only this one**.
