### ISSUE TITLE
(not a copy of #19) any other ways to run sm64coopdx on android besides winlator?

### ISSUE THREAD

**Issue by Aust20156** [coop-deluxe/sm64coopdx#279]
i cannot find the xdelta file help?

**Comment by Cooliokid956** [comment]
the what

**Comment by Bloxxel64** [comment]
the who?

**Comment by Brob2nd** [comment]
I think he's asking for a xdelta file, a patch file, He probably thinks sm64coopdx is a rom hack
sm64coopdx isn't a rom hack that you need to patch with a SM64 rom in order to play it, sm64coopdx is a decompilation of Super Mario 64 with added online multiplayer, you need to download it from the Releases section from this repository ( https://github.com/coop-deluxe/sm64coopdx/releases/tag/v1.0.1 ) and when you open the game, you need to drag your Super Mario 64 [U] rom there.

**Comment by Aust20156** [comment]
No no no, i am doing it cuz i'm trying to modify the baserom with dx' files so i can run it on Android with z64 emulators |:

**Comment by Aust20156** [comment]
And i need a xdelta file to patch it so what

**Comment by Bloxxel64** [comment]
> No no no, i am doing it cuz i'm trying to modify the baserom (legally) with dx' files so i can run it on Android with z64 emulators and since this game uses it's files, i should be able to patch it. |:

i dont think you understand, coop is a decomp mod, NOT A ROMHACK.

**Comment by Bloxxel64** [comment]
you cant emulate it as it uses operating system code, not n64 code, for stuff like rendering.

**Comment by Aust20156** [comment]
How run on android (i know winlator works but i am on a 32bit device)
Any other options?

**Comment by Aust20156** [comment]
(Btw copilot said there was a xdelta file and they lied)

**Comment by Aust20156** [comment]
Waiting...

**Comment by frog8412** [comment]
mobox might be an option

**Comment by frog8412** [comment]
> (Btw copilot said there was a xdelta file and they lied)

‼️ don't ask ai about things that are not well known ‼️

**Comment by robertkirkman** [comment]
> How run on android (i know winlator works but i am on a 32bit device) Any other options?

please dont open more issues on other projects, this is the repo of the Windows version of sm64coopdx 1.0.1 or sm64ex-coop 37.1, and has stated that [Android is not in scope for the focus of this repo](https://sm64coopdx.com/), For the distros FreeBSD, OpenBSD, Android and Alpine you should continue to wait for [this issue](https://github.com/robertkirkman/sm64ex-coop/issues/19),

because of how UNIX-like operating systems work, it turns out that a lot of evidence points to the development code and outline for supporting them being partially intertwined with the code involved with fixing build errors and crashes in the two distros that are targeted by this sm64coopdx repository, GNU/Linux and MacOS. So you can read about steps being taken on code that will _probably_ be shared between the builds for several major UNIX-like operating systems, in the three issues #275 , #276 , #158 . If you have comments that are relevant in a way that affects *many UNIX-like operating systems simultanously* , you can post them there, but if you have more comments that are specific to Android, they should be posted in the other issue [here](https://github.com/robertkirkman/sm64ex-coop/issues/19).

**Comment by Aust20156** [comment]
So does mobox work with android 9, 32-bit? (Also show tutorial how to install and use)

**Comment by frog8412** [comment]
> So does mobox work with android 9, 32-bit? (Also show tutorial how to install and use)

It does, just search up mobox in google

**Comment by fon10984-source** [comment]
> i cannot find the xdelta file help?

Shut fuck tell Mario sonic
And kunch

**Comment by DarknessBoy2010** [comment]
Hi. I'm an sm64 fan and i have good news. Theres an actual sm64coopdx port on android. Lemme get the link: https://github.com/ManIsCat2/sm64coopdx
Also you need to provide an unmodified rom. Skill issue

**Comment by Bloxxel64** [comment]
why are we necroing an old ass issue

**Comment by Aust20156** [comment]
> Hi. I'm an sm64 fan and i have good news. Theres an actual sm64coopdx port on android. Lemme get the link: https://github.com/ManIsCat2/sm64coopdx Also you need to provide an unmodified rom. Skill issue

Yeah, last Christmas I got a 64-bit device, and I love that port! Very old Issue btw, also I shouldn't  have listened to that clanker.
