### ISSUE TITLE
TARGET_RPI hangs on build?

### ISSUE THREAD

**Issue by futurepr0n** [coop-deluxe/sm64coopdx#313]
**Describe the bug**
I have tried to build using the target_rpi on a linux machine as well as on a rpi itself. on the RPI it basically begins to hang as it compiles. On the Linux PC side I was pretty much successful however there was a liblua arm dependency that Im not sure how to get around. I am on an intel linux machine, I tried to install the liblua and comment out the discord related stuff but it seems like it was not happy no matter what. Any tips on how to successfully build for RPI? Or is this some legacy thing thats not really possible to do anymore.

**To Reproduce**
get the repo, and extract assets from the rom, begin `make TARGET_RPI=1` 

**Expected behavior**
A complete and successful build 

**Screenshots**
None available at this time.

**Desktop (please complete the following information):**
RPI natively building on raspbian hangs
building on ubuntu 22 on laptop (intel) fails due to liblua arm

**Additional context**

**Comment by owokitty** [comment]
> RPI natively building on raspbian hangs
> i tried to install the liblua  and comment out the discord related stuff but it seems like it was not happy no matter what

I don't have a raspberry pi, but I created the only Mario 64 port to Beaglebone black which is like an off-brand raspberry pi, so I have some experience with the subject (to be clear don't use a beaglebone black version though it has parts that raspberry pis dont have)

- you will probably want to use the development branch of sm64coopdx for now to avoid a crash when near piranha plants in ARM builds for Linux
- In #275 I posted a video showing a version of sm64coopdx running on an ARM environment that is binary compatible with 64-bit raspberry pis running GNU/Linux, so building it like I do would result in a binary that works on any 64-bit raspberry pi. 
- However, unfortunately the code of the build I showed in the video is not quite ready to upload because it's a work in progress and also, it was compiled using a new WIP build process that includes the unfinished alternative audio extractor code from one of my other posts #158 
- If me or someone else eventually builds an **aarch64 (64-bit ARM) AppImage** or a Universal architecture AppImage, that build will be possible to run on Raspberry Pi

You don't specifically need the WIP audio extracting code for ARM support, which is why I haven't uploaded an entire buildable fork yet, it's just because me doing them at the same time causes the code of both features to be unfortunately intertwined in my version. 

If you really need this to be working on Raspberry Pi soon though, you could let me know and I would try to upload a raspberry pi compatible version (patches, repos or binaries) as soon as I finish the minimum completeness level I am comfortable uploading for the GNU/Linux ARM version shown in my video.

**Comment by futurepr0n** [comment]
closing this and will continue to work with owokitty regarding any dx related pi builds if they become available in the future.
