### ISSUE TITLE
I-Frames in the air for Ground Pounding

### ISSUE THREAD

**Issue by SausRelicsSSJ2** [coop-deluxe/sm64coopdx#344]
The startup for groundpound, for as long as it is, can be hit and deactivated with a jumpkick or a dive, making it unviable in a lot of situations. Giving GP's Invincibility frames in the air makes players think twice before just jumping in to stop the attack.

**Comment by yoyeet961** [comment]
this is not the place for mod suggestions like that

**Comment by EmeraldLoc** [comment]
> this is not the place for mod suggestions like that

This is not a mod suggestion, he is suggesting change to the pvp system in coopdx. While this could become a mod (rather easily), he finds it to be an issue with coopdx pvp as a whole that should be resolved. Personally, I disagree with this change, since GP's should be hard to hit as they do the most damage, however that is for an admin of the repo to decide.

**Comment by yoyeet961** [comment]
Oh
