### ISSUE TITLE
Two specific players can not coexist in a server

### ISSUE THREAD

**Issue by RisingArtist** [coop-deluxe/sm64coopdx#558]
**Describe the bug**

Frequently, I'll join the server and it would kick the other out of the server after roughly about 30 seconds. 

This is only happens between me and a specific player; Neither the mutual friend (our host) nor other players get disconnected when one of us joins the server. 

**To Reproduce**
1. Create a vanilla private server with a simple password
2. Either let the other player join the server or join before they do. 
3. Wait about a minute after both players join the server. 
4. Either you or the other player gets disconnected. 

Generally when we get disconnected, we will see that the **other** player got disconnected at the top right. They didn't actually disconnect. 

In one instance, my friend got the crash screen below in the **Screenshot** section. 

**Expected behavior**

For both of us to stay connected in a server. Neither one of us gets disconnected under a minute. 

**Screenshots**

This screen appeared on my friend's side. 
![SM64 Crash Report Screen](https://github.com/user-attachments/assets/d24c3f38-a6f4-454a-8539-60631d851c74)

**Additional context**
- Our computers are **identical**. We build them together with the same parts.
- On occasion (possibly 1 out of 20 server resets), this issue doesn't occur. 
- It does not matter who is hosting the server. 

https://github.com/user-attachments/assets/358247aa-9b15-4ea3-91d9-eea99e0f0738

**Comment by Flower35** [comment]
The only explanation for disconnects that I can think of must be poor (unstable) network connection and one of these two players reaching a disconnect timeout (reconnect timer running out) on a random chance.

https://github.com/coop-deluxe/sm64coopdx/blob/f85b8419afc6266ac0af22c5723eebe3effa1f7d/src/pc/network/network.c#L650-L652

---

As for the crash, there were three conditions for it to happen:
- player must host (or join) a server with 0 mods
- must have invalid network connection (either broken "Direct Connection" or disconnect on timeout)
- player must have viewed the "player list" panel and kept it open, while being disconnected/reconnected

https://github.com/coop-deluxe/sm64coopdx/blob/f85b8419afc6266ac0af22c5723eebe3effa1f7d/src/pc/djui/djui_panel_playerlist.c#L65-L70

The crash happened the moment `gNetworkType` became `NT_NONE`, and `gDjuiModList` was `NULL` because the "mod list" panel is not created when there are 0 active mods:

https://github.com/coop-deluxe/sm64coopdx/blob/f85b8419afc6266ac0af22c5723eebe3effa1f7d/src/pc/djui/djui_panel_modlist.c#L15-L22

---

**Comment by docfail** [comment]
I am the other player spoken of in this bug report. I can confidently rule out an unstable/poor network connection. As emphasized in the bug report, I am able to join the exact same server with the same individuals at the same times and have no problems whatsoever, consistently. I have never once been disconnected randomly from a server, except for when @RisingArtist joins the server, at which point I will be disconnected ~90% of the time after a short period of time, the other ~10%, either _he_ gets disconnected instead, seeing the same symptoms (a message saying that *I* was disconnected from the server as he is kicked from the game), or, very very rarely, maybe ~1% of the time somehow we both remain connected with no issues for a while, until the server restarts, at which point seemingly we're rolling the dice again, our connecting/disconnecting has no effect, only the server restarting gives a chance for us to potentially stay connected at the same time. We have tried with different hosts, each several times. When @RisingArtist hosts, I cannot connect to his server, and vice versa, it simply loads forever. When anyone else hosts, it's fine.

**Comment by AgentXLP** [comment]
Maybe it's CoopNet being weird then. This has been resolved in 1.1
