### ISSUE TITLE
Failed to connect to player "unknown"

### ISSUE THREAD

**Issue by Skupitajo** [coop-deluxe/sm64coopdx#571]
![Uploading image-1.png…]()
Hi guys. I have a problem that came up recently and from what I see it's not very common. I can't join public or private servers, it gives me an error message every time I try. Please, if anyone knows what I can do to fix this error, I would really appreciate it.
PD: My internet connection is via "Ethernet" and works perfectly in other applications and games, so I doubt it's something related to that.
Before joining any server, on the left side I get "..." And on the right The version is "37.3".
The error messages I get are the following: "Disconnected: Server Closed" "Failed to connect to player 'unknown'".

**Comment by Emeraldsniper** [comment]
Just because you have "good or decent internet" doesn't mean you'll have proper times with Coop. It's dialed down more than just "good internet."
95% of the time it's likely your own net or other host's net not liking P2P connectivity that CoopNet uses. Other times it could be your firewall not letting Coop just play normally with its services.
You'll have to just find out if your ISP allows such connections and if you really have stable connections with it.

**Comment by martenmario64** [comment]
im having the same issue
