### ISSUE TITLE
Reopening the game makes everything reset

### ISSUE THREAD

**Issue by windows10-gthb** [coop-deluxe/sm64coopdx#73]
**Describe the bug**
Any changes after reopening the game would be reset back to default

**To Reproduce**
1. Open the game
2. Make any changes (change key mappings, enable sm64ex-coop compatibility, get some stars, etc.)
3. Reopen the game
4. Everything that was changed would be reverted to default.

**Expected behavior**
Every changes would be saved.

**Screenshots**
Before:
![image](https://github.com/coop-deluxe/sm64coopdx/assets/160930327/1ddea7da-4f5b-49cd-887f-2c9bd275e48f)
After:
![image](https://github.com/coop-deluxe/sm64coopdx/assets/160930327/cf78d40c-6138-47cc-9d22-4710000cf873)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser Chrome
 - Version of what? Chrome? 121.0.6167.185. sm64coopdx? 0.1.4.

**Comment by Agent-11** [comment]
This issue again, can you send the full path to the sm64coopdx exe?

**Comment by windows10-gthb** [comment]
E:\Downloads\coopdx-patcher\sm64coopdx

**Comment by windows10-gthb** [comment]
that's the folder where it's located

**Comment by windows10-gthb** [comment]
the exe is called sm64coopdx

**Comment by Agent-11** [comment]
This *might* be because of it being on a different drive, try your C drive.

**Comment by windows10-gthb** [comment]
Nope, it still resets.

**Comment by Agent-11** [comment]
Go to %AppData%\sm64ex-coop and see if there is a file called `sm64config.txt` there

**Comment by windows10-gthb** [comment]
The folder is empty.

**Comment by windows10-gthb** [comment]
it's not

**Comment by Agent-11** [comment]
Hmm...

**Comment by uuphoria2** [comment]
> it's not

Mannually make it by making a file within %Appdata%/sm64ex-coop called: sm64config.txt and put the default data here: `"fullscreen false

key_a 57

key_b 51

key_start 28

key_r 54

key_z 37

key_cup 328

key_cdown 336

key_cleft 331

key_cright 333

key_stickup 17

key_stickdown 31

key_stickleft 30

key_stickright 32" ` Coop will automatically config it for mods and after selecting language at the menu press `Options` `Controls` And configure both `N64 Binds` and `Extra binds` to what you like this is what i did for older coopdx versions (when i first played it) cuz sometimes my file got corrupted

**Comment by uuphoria2** [comment]
If my solution doesnt work in your antivirus which should be microsoft defender then make an exclusion for the file sm64config.txt after you do the other step

**Comment by Agent-11** [comment]
Try putting the game on a Windows Defender excluded folder, see if that does anything.

**Comment by windows10-gthb** [comment]
Nothing works rn.
Also I noticed that when I press "Open AppData" it opens sm64coopdx folder

**Comment by Agent-11** [comment]
This is so strange wtf

**Comment by windows10-gthb** [comment]
opening the game like `sm64coopdx.exe --savepath .` fixed the issue, thx

**Comment by Agent-11** [comment]
Ohh okay.

**Comment by Flower35** [comment]
Hello, I wanted to comment on that because recently I had similar issue and found the cause of the problem (settings and tmp mods not being saved).

To put it shortly, the issue is path encodings. This will persist for every user that has "diacritics" (Unicode characters) in their User profile directory name on Windows OS.

---

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/pc/platform.c#L127

In the `sys_user_path()` procedure (`"src/pc/platform.c":127`), the `SDL_GetPrefPath("", "sm64ex-coop")` call returns an `UTF-8` encoded path to the `AppData\Roaming` user directory.

However, that path is passed to procedures `fs_sys_dir_exists()` and `fs_sys_mkdir()`, both returning `false`, since they expect a path encoded in the "ancient" `ANSI`/`OEM` CodePage encoding.

---

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/pc/fs/fs.c#L455

`fs_sys_mkdir()` points to `msvcrt._mkdir`  which internally calls `Kernel32.CreateDirectoryA`.

These `ANSI` and `UTF-8` CodePages are not interchangable on Windows! (unline Linux and macOS where all paths are stored as `UTF-8`)

---

Launching the game with `sm64coopdx.exe --savepath .` (or `sm64coopdx --savepath !`) is an OK temporary solution, if the game is installed in an ASCII-complaint path (standard English letters, for better paths handling compatibility).

However, the proper solution would be to use "wide" char (`UTF16-LE`) functions like `_wmkdir()` (or `CreateDirectoryW()`), converting the path returned from `SDL_GetPrefPath()` with `MultiByteToWideChar(CP_UTF8, ...)` (or calling `SHGetFolderPathW()` directly), etc.

---

**Comment by Agent-11** [comment]
Wow, this is really helpful knowledge to go towards finally fixing this, thank you. I'll work on it soon.
