### ISSUE TITLE
The mouse does not work with DirectX to play in the game.

### ISSUE THREAD

**Issue by SarksJK** [coop-deluxe/sm64coopdx#93]
My first time commenting here regarding any inconvenience. Since, I realized that it is not the most optimal to do it through "Twitter/X, now I will do it through github. 

Speaking about the bug, it happens that when you are patching the game with the DirectX option, when you start playing with the camera function with the mouse the game simply does not detect it. Honestly, at the beginning (when I updated the game) I had not noticed the error, since I play with a controller for convenience (the letter A is missing from my keyboard XD), But when I installed the game for two of my friends (in the same way with DirectX) I did not detect their mouse when playing. It's something strange, since the mouse does work to navigate the menu, but when you enter the game it stops working in the game directly. In fact, in the controls setup part, it doesn't even detect the mouse touch as a button, it just ignores it. 

It's a bit sad, mostly for one of my friends because he doesn't have a controller to play and only a mouse and keyboard (and there are probably many people like that with the same situation). It is an error isolated to DirectX, since when changing to OpenGL the mouse works perfectly in the game. In the case of one of my friends, his laptop runs the game much better with DirectX than with OpenGL, so I am making this report so that in the future update you can fix the error.

@Agent-11 @AngelicMiracles @FluffaMario

**Comment by Agent-11** [comment]
DirectX is hardly supported and the only reason it hasn't been removed despite
* Being more prone to showing displaylist corruption
* Missing input features like the mouse
* No loading screen
* Every keybind showing up as `?` I believe?
* The window behaving in a buggier way
Is because some people have problems running OpenGL somehow.

We are probably going to focus on fixing up DirectX next major release and trying to add support for the features it's missing. This unrelated to DirectX but we are probably going to fix a problem with the SDL2 rumble not working on some controllers too.

**Comment by SarksJK** [comment]
I read it as soon as he responded but I decided to respond until now. I
understand, thank you very much for taking the time to respond. I'll keep
an eye out for future coopdx updates. Greetings and have a good day my
favorite agent
