### ISSUE TITLE
The game crashes when i'm hosting a game

### ISSUE THREAD

**Issue by windows10-gthb** [coop-deluxe/sm64coopdx#98]
**Describe the bug**
basically the game crashes when starting to host

**To Reproduce**
1. Start hosting a lobby with Day Night Cycle DX and other mods while your WiFi can't connect to Coopnet
2. See error

**Expected behavior**
The lobby would load in.

**Screenshots**
![image](https://github.com/coop-deluxe/sm64coopdx/assets/160930327/03828183-2ab0-450d-94cb-edfb2e1b1baf)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser Google Chrome
 - Version 123.0.6312.58

**Additional context**
I reinstalled the game because Coopnet wasn't working on my home WiFi, now this happens

**Comment by Agent-11** [comment]
Will look into.

**Comment by Flower35** [comment]
The game crashes while dereferencing `gNetworkPlayerLocal` in `nametags_render()`

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/pc/nametags.c#L51

Because the connection to **"CoopNet"** failed, `network_player_connected()` is never called and thus `gNetworkPlayerLocal` stays at `NULL`.

Also, `network_player_connected_count()` returns `0` (instead of the expected `1`), and the game is in a ghost state (unknown network type, no mods loaded).

---

Since the loop in `nametags_render()` calls `is_player_active()` for all network players anyways (if either at least 2 players are connected, or including the local player if `gNametagsSettings.showSelfTag` option is set),

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/pc/nametags.c#L61

I would suggest simplifying the first check to:
```c
if (find_object_with_behavior(bhvActSelector) != NULL) { return; }
```

or, if that network-player-check is still required for some reason:

```c
if (((gNetworkPlayerLocal != NULL) && !gNetworkPlayerLocal->currAreaSyncValid) ||
    find_object_with_behavior(bhvActSelector) != NULL)
{
    return;
}
```

---

Another issue is that when server hosting fails, you CANNOT quit the game to main menu (to reconnect or to join other server), because `network_shutdown()` (called from `djui_panel_pause_quit_yes()`) silently returns at the `gNetworkType` check.

https://github.com/coop-deluxe/sm64coopdx/blob/30ccad30a8be27e3f0fa34fd2ab27303a65eb4f4/src/pc/network/network.c#L630

The only option is to forcibly shutdown the game by closing the window or the `sm64coopdx.exe` process.

**Comment by Agent-11** [comment]
God you are such a major help to fixing bugs, thank you dude.

**Comment by Agent-11** [comment]
Fixed

**Comment by frog8412** [comment]
now i get this error when hosting (the transition appears for a second and then it crashes)
![image](https://github.com/coop-deluxe/sm64coopdx/assets/160930327/00717437-7c3c-4887-a307-2b2c019b0d13)
